### ISSUE TITLE
Warnings when click on icon

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/icon_browser#12]
Installed using the `prerelease` branch

Load page. Click on icon

>Warning: Undefined global variable $theme_key in _icon_from_theme() (line 137 of /app/docroot/core/includes/icon.inc).
>Warning: Undefined array key "" in _icon_from_theme() (line 158 of /app/docroot/core/includes/icon.inc).

**Comment by indigoxela** [comment]
Same here. :wink:

**Comment by laryn** [comment]
Thanks @yorkshire-pudding and @indigoxela -- I found the same. I opened it as a core issue but will leave this one open as well until we figure out for sure if it's something I did wrong in this module or if it's actually a core issue:
 - https://github.com/backdrop/backdrop-issues/issues/6510

**Comment by laryn** [comment]
@yorkshire-pudding or @indigoxela -- if either of you have your icon browser test site open yet, does the linked PR solve it for you? I guess that 'path' may not be needed?

**Comment by indigoxela** [comment]
I belief, it's core.

If I set `backdrop_theme_initialize();` inside function _icon_from_theme() everything works.
Not matter, where I try backdrop_theme_initialize in your module - the problem persists.

The error reminded me, that the theme information is usually available for themes, but not for modules.

**Comment by indigoxela** [comment]
@laryn yes, the patch (one liner) fixes it. :+1:

**Comment by yorkshire-pudding** [comment]
Was getting a cup of tea, but can also confirm this fixes it.  Thanks @laryn

**Comment by laryn** [comment]
🍵 
I've also renamed the branch, FYI. Not sure why I started that way, to be honest.
