### ISSUE TITLE
Icon Browser doesn't fully support hook_icon_info().

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/icon_browser#15]
The sample code for [`hook_icon_browser()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_icon_info/1) allows us to pass an empty array for icon SVGs that are in a module's `icons` subdirectory:

```php
function hook_icon_info() {
  // For icons simply located in a module's "icons" directory, just provide the
  // name of the file (minus ".svg") as the array key. This can be used to
  // override core icons if the name of the icon matches a core one, or provide
  // new ones if the name is unique.
  $icons['my-module-icon1'] = array();

  // <snip>
  return $icons;
}
```

Which means that we ought to be able to do this in a module with two icons in its `icons` subdirectory:

```
/**
 * Implements hook_icon_info().
 */
function icon_browser_test_icon_info() {

  $icons['acorn-fill'] = array(); // Override the core 'acorn-fill' icon
  $icons['test-acorn-fill'] = array(); // Create our own new icon

  return $icons;
}
```

However, if we do, there are two problems. First, in the Icon Browser, the name of overridden `acorn-fill` is lost:

![image](https://github.com/backdrop-contrib/icon_browser/assets/29214084/5e35e275-2cd8-4c8d-b902-26ba343db13d)

Second, if we set "Module" as provider, we get two icons with no name:

![image](https://github.com/backdrop-contrib/icon_browser/assets/29214084/c7fb596e-5e84-4ec6-8018-da51b395024f)

Attached is a small test module that can be used to verify the issue.

[icon_browser_test.zip](https://github.com/backdrop-contrib/icon_browser/files/15355366/icon_browser_test.zip)

**Comment by laryn** [comment]
@bugfolder Looks like we filed exactly the same PR. 😆

**Comment by bugfolder** [comment]
At the same time, it appears. Keep whichever one you want.

**Comment by laryn** [comment]
Thanks @bugfolder -- merged!
