### ISSUE TITLE
Testing with contrib modules that have implemented the new core Icon API

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/icon_browser#3]
FYI - I added the dev branch of On The Web module to test the Icon Browser with icons provided by contrib modules. 

This was the result. Keeping in mind that both modules are still working towards implementing this feature. I still find it interesting and exciting to see this progress. Maybe it's helpful for discussion.

![image](https://github.com/backdrop-contrib/icon_browser/assets/3144571/e44e6911-e04a-43b4-b79f-6e10b6b2f117)

**Comment by laryn** [comment]
@stpaultim I made a few tweaks and cleanup this morning. Here's what I'm seeing right now with the latest code:
![image](https://github.com/backdrop-contrib/icon_browser/assets/871421/ab1e2ae7-8ff6-42a7-bd8e-f45b8bbff693)

![image](https://github.com/backdrop-contrib/icon_browser/assets/871421/d64bcf12-cd3c-4c36-9a69-2e4b29d5a76a)

The OTW fonts may need minor adjustment to make them colorable.

**Comment by laryn** [comment]
Closing since module icons seem to be showing up as I'd expect at this point.
