### ISSUE TITLE
Core Icons - "Icon Not Found"

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/icon_browser#4]
Sometimes I feel like a real killjoy when doing early testing on a module or PR. ;-)

@laryn Somethings are fixed, but one thing seems to have been broken with latest commits. 

All the icons are showing up nicely for the On The Web module now, good work. But, none of the core icons are showing up. Inspecting the page shows this:

![image](https://github.com/backdrop-contrib/icon_browser/assets/3144571/8f57fbba-b1be-44f3-b04b-38449ce7e9a7)

The actual page looks like this:

![image](https://github.com/backdrop-contrib/icon_browser/assets/3144571/3e9697fe-e354-488b-bcbc-414309c85c64)

Again, the contrib filter shows the icons just fine. It's only a problem with Core icons.

**Comment by laryn** [comment]
@stpaultim Can you tell my development time sometimes comes in 5-minute bursts? :sweat_smile: 

This should be fixed in https://github.com/backdrop-contrib/icon_browser/commit/a771296a5373924eeec1b05cc2482fd4ac2bbac3

**Comment by stpaultim** [comment]
> Can you tell my development time sometimes comes in 5-minute bursts? 😅

I appreciate whatever time you can spare! 

I confirmed that this fixed the problem on my local install.
