### ISSUE TITLE
Add information to browser on which module or theme provided the icons

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/icon_browser#6]
We have the ability to filter icons and show those provided by modules. 

Would it be possible or helpful to also provide information about which module, theme, or core provided each icon?

![image](https://github.com/backdrop-contrib/icon_browser/assets/3144571/efb097bb-6359-4b3e-8a60-a1563d8848d7)

**Comment by laryn** [comment]
@stpaultim I was thinking the same thing. Early work on this is in the latest code.

**Comment by stpaultim** [comment]
Nice work.

![image](https://github.com/backdrop-contrib/icon_browser/assets/3144571/db062836-5f4d-4dff-bfb1-af080e390c8c)

**Comment by stpaultim** [comment]
I would bold the words "Provided by". Treat them as a label.

I'm not sure if you must indicate "module" or "theme" here, but it does not hurt. Removing it would simplify the UI a bit, but not much.

**Comment by laryn** [comment]
I think it's helpful to have the provider type listed for the detail view -- e.g. if you are filtering from all providers on a keyword, it brings some additional clarity.

**Comment by stpaultim** [comment]
My only thought is that the information is not as easy to see on the page as it could be. In some way highlighting the "provided by" could help, a little bit.

However, I think what you have is pretty good and I would be happy to close this issue if you think it's good enough.

**Comment by laryn** [comment]
This should be fixed in https://github.com/backdrop-contrib/icon_browser/commit/2e0d3b54381d10de117bdfe4c0a7b4ce80adfa16

**Comment by stpaultim** [comment]
@laryn - I like the bold label, but the results have dissappeared for me. 

![image](https://github.com/backdrop-contrib/icon_browser/assets/3144571/b52c0845-7d99-4641-9cdb-3641ae09f32c)

**Comment by laryn** [comment]
Thanks @stpaultim -- good catch. A slight regression was introduced when adding the pager (the confusion between the provider key and icon name again). This also helped me find a place to improve the returned result when a request is made to `icon_browser_icon_details()` and no icon is found with that key. Fixed in https://github.com/backdrop-contrib/icon_browser/commit/d864965a1b84e89205e6f11959e5a33f57b8da47
