### ISSUE TITLE
Reset selected icon

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/icon_browser#8]
This seems a little weird to me and could be made a little better.

Steps to reproduce:

1) Install Icon Browser module and On the Web
2) Filter for icons provided by modules
3) Select "Delicious" icon
4) Change filter to show all icons

Note "Delicious" icon is still highlighted at top. 

5) Click "Reset"

Note "Delicious" icon is still highlighted at top

![image](https://github.com/backdrop-contrib/icon_browser/assets/3144571/e142436e-efab-4059-94ff-a0af6c962551)

I think maybe the selected icon should be reset to NONE at step 4. If not at step 4, then certainly at step 5 when one selects "Reset".

**Comment by laryn** [comment]
I also noticed that saving defaults also saves the keyword, which is probably not commonly expected.

**Comment by laryn** [comment]
This should be fixed in https://github.com/backdrop-contrib/icon_browser/commit/6b7b64bc9fd5f6f799fa176849541937b5cc98ed

**Comment by stpaultim** [comment]
@laryn Confirmed. Thank you!
