### ISSUE TITLE
Add paging

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/icon_browser#9]
The list of icons is huge. Add a pager.

**Comment by docwilmot** [comment]
Attmpt at adding paging. The `per_page` variable should probably be assigned to a constant; using 110 items because on my local the grid is 11 icons wide and that seemed a reasonable number. 🙂

**Comment by laryn** [comment]
Thanks @docwilmot!

**Comment by stpaultim** [comment]
Very nice @docwilmot !
